[View in Colaboratory](https://colab.research.google.com/github/clee1994/DLclass/blob/master/HW03_backprop.ipynb)

In [0]:
import numpy as np

def sigmoid(x, Deriv=False):
  if Deriv:
    out = sigmoid(x)
    return out*(1-out)
  else:
    return 1/(1+np.exp(-x))
  
  
class NN:
  
  # define some NN params
  numLayers = 2
  shape = None
  weights = []
  
  
  
  # Initialize the network based on the number of neurons per layer
  def __init__(self,neuronsPerLayer):
    """Initialization of Neural Network"""
  
  # initialize some parameters
    self.numLayers = len(neuronsPerLayer) - 1
    self.shape = neuronsPerLayer
    
    # null the network
    self._layerInput=[]
    self._layerOutput=[]
    
    #initialize the weights
    for (l1,l2) in zip (neuronsPerLayer[:-1],neuronsPerLayer[1:]):
      self.weights.append(np.random.normal(scale=.1,size=(l2,l1+1))) # List of weights
  
  #Create the forward pass
  def forward(self,input):
    """Define the forward pass for this network"""
    numExamples = input.shape[0]
    
    self._layerInput =[]
    self._layerOutput =[]
    
    for idx in range(self.numLayers):
      if idx == 0:
        intermediate = np.vstack([input.T, np.ones([1,numExamples])])
      else:
        intermediate = np.vstack([self._layerOutput[-1],np.ones([1,numExamples])])        
      # for each layer 
      
      #value before activation is the weight times the previous input + bias
      layerInput = self.weights[idx].dot(intermediate)
      
      #Store all inputs and outputs
      self._layerInput.append(layerInput)
      self._layerOutput.append(sigmoid(layerInput))

    return self._layerOutput[-1].T
    
  def backward(self,input,target,lrate = .1):
    """Define the backward pass for this network"""
    Err = []
    numExamples = input.shape[0]
    
    #In order to update the weights, first implement the forward pass    
    self.forward(input)
    
    # now work backwards through the layers
    for rev_idx in reversed(range(self.numLayers)):      
      # For every layer find the error at that layer backwards
      
      # First calculate the gradient due to the sigmoid at this layer
      sigmoidGradient = sigmoid(self._layerInput[rev_idx],True)
      
      if rev_idx == self.numLayers -1: # if last layer find loss vs. Target        
        output_Err = self._layerOutput[rev_idx]-target.T
        Loss = np.sum(output_Err**2)

      else:
        pass
      
    return Loss
    
Input = np.array([[0,0,0,0],[1,1,1,1],[0,1,1,1],[1,0,1,1]])
Target = np.array([[0.0],[0.0],[1.0],[1.0]])


# Neurons per layer
# Input = 4
# Hidden1 = 4
# Hidden2 = 3
# Output = Target = 1
bpn = NN((4,4,3,1))

# print("The initial weights are:",NN.weights)

Error = bpn.backward(Input, Target)
Output = bpn.forward(Input)

print ('Input \t\tOutput \t\tTarget')
for i in range(Input.shape[0]):
    print ('{0}\t {1} \t{2}'.format(Input[i], Output[i], Target[i]))
      
  

maxIterations = 100000
minError = .001
print ('\n')
for i in range(maxIterations + 1):
    Error = bpn.backward(Input, Target)
    if i % 2500 == 0:
        print("Iteration {0}\tError: {1:0.6f}".format(i,Error))
    if Error <= minError:
        print("Minimum error reached at iteration {0}".format(i))
        break


Input 		Output 		Target
[0 0 0 0]	 [0.51788474] 	[0.]
[1 1 1 1]	 [0.51794725] 	[0.]
[0 1 1 1]	 [0.51784351] 	[1.]
[1 0 1 1]	 [0.51799827] 	[1.]


Iteration 0	Error: 1.001275
Iteration 2500	Error: 1.001275
Iteration 5000	Error: 1.001275
Iteration 7500	Error: 1.001275
Iteration 10000	Error: 1.001275
Iteration 12500	Error: 1.001275
Iteration 15000	Error: 1.001275
Iteration 17500	Error: 1.001275
Iteration 20000	Error: 1.001275
Iteration 22500	Error: 1.001275
Iteration 25000	Error: 1.001275
Iteration 27500	Error: 1.001275
Iteration 30000	Error: 1.001275
Iteration 32500	Error: 1.001275
Iteration 35000	Error: 1.001275
Iteration 37500	Error: 1.001275
Iteration 40000	Error: 1.001275
Iteration 42500	Error: 1.001275
Iteration 45000	Error: 1.001275
Iteration 47500	Error: 1.001275
Iteration 50000	Error: 1.001275
Iteration 52500	Error: 1.001275
Iteration 55000	Error: 1.001275
Iteration 57500	Error: 1.001275
Iteration 60000	Error: 1.001275
Iteration 62500	Error: 1.001275
Iteration 65000	Error: 1.0012